theme = "tokyonight_storm"

[editor]
true-color = true
mouse = false
bufferline = "always"
cursorline = true
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
right = ["total-line-numbers", "diagnostics", "selections", "position", "file-encoding"]
left = ["mode", "file-base-name", "spinner"]

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-k = ["add_newline_above", "move_line_up"]
A-j = ["add_newline_below", "move_line_down"]
C-n = ["goto_next_buffer"]
C-p = ["goto_previous_buffer"]

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
