theme = "tokyonight_storm"

[editor]
line-number = "relative"
true-color = true
mouse = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
right = ["total-line-numbers", "diagnostics", "selections", "position", "file-encoding"]
left = ["mode", "file-base-name", "spinner"]

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]